on:
  workflow_dispatch:

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-13
        - macos-latest
        - macos-11

    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          #echo "runner ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
          sudo sysadminctl -addUser mitmproxyuser -admin
          pip3 install mitmproxy
          # start mitmdump in simple mode for now to generate CA certificate
          sudo -u mitmproxyuser -H bash -e -c "cd /Users/mitmproxyuser && mitmdump &"     
