on:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-13
        - macos-latest
        - macos-11

    runs-on: ${{ matrix.os }}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@repro
