on:
  workflow_dispatch:

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-13
        - macos-latest
        - macos-11

    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          #echo "runner ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
          #sudo sysadminctl -addUser mitmproxyuser -admin
          pip3 install mitmproxy
          sudo -H bash -e -c "mitmdump &" 
