on:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-13
        - macos-latest
        - macos-11

    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          #echo "runner ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
          sudo sysadminctl -addUser mitmproxyuser -admin
        
          # install requests for mitm plugin
          pip3 install mitmproxy requests
          # sudo cp mitm_plugin.py /Users/mitmproxyuser/mitm_plugin.py
        
          # start mitmdump in simple mode for now to generate CA certificate
          sudo -u mitmproxyuser -H bash -e -c "cd /Users/mitmproxyuser && mitmdump &"        
