on:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-13
        - macos-latest
        - macos-11

    runs-on: ${{ matrix.os }}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@repro
      
      - uses: actions/checkout@v3
      
      # test github-script CA
      - name: github-script
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.issues.listLabelsOnIssue({
              issue_number: 2,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
      # test gh CA
      - name: gh api
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/issues/1/labels

      # test curl CA
      - name: curl
        run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://Api.github.com/repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/labels
